# requirements for github action
- src: robertdebock.bootstrap

# requirements to install galaxy
- src: https://github.com/galaxyproject/ansible-galaxy
  version: 0.10.14

- src: https://github.com/galaxyproject/ansible-nginx
  version: 0.7.1

- src: https://github.com/galaxyproject/ansible-postgresql
  version: 1.1.6

- src: https://github.com/galaxyproject/ansible-postgresql-objects
  version: 1.2.0

- src: https://github.com/geerlingguy/ansible-role-pip
  version: 2.0.0

- src: https://github.com/galaxyproject/ansible-miniconda
  version: 0.3.1

# - src: usegalaxy_eu.galaxy_systemd

- src: https://github.com/usegalaxy-eu/ansible-certbot
  version: 0.1.11

# - src: galaxyproject.proftpd

- src: https://github.com/galaxyproject/ansible-role-tusd
  version: 0.0.1  

- src: https://github.com/galaxyproject/ansible-cvmfs
  version: 0.2.14

# - src: https://github.com/Laniakea-elixir-it/ansible-role-laniakea-galaxy-interactive-tools

- src: https://github.com/Laniakea-elixir-it/ansible-role-laniakea-cvmfs-client-config
