# requirements for github action
- src: robertdebock.bootstrap

# requirements to install galaxy
- src: galaxyproject.galaxy
  version: 0.10.4

- src: galaxyproject.nginx
  version: 0.7.0

- src: galaxyproject.postgresql
  version: 1.1.1

- src: galaxyproject.postgresql_objects
  version: 1.2.0

- src: geerlingguy.pip
  version: 2.0.0

- src: uchida.miniconda
  version: 0.3.0

# - src: usegalaxy_eu.galaxy_systemd

- src: usegalaxy_eu.certbot
  version: 0.1.5

# - src: galaxyproject.proftpd

- name: galaxyproject.tusd
  version: 0.0.1  

- src: galaxyproject.cvmfs
  version: 0.2.14

- src: laniakea.galaxy_interactive_tools

- src: laniakea.cvmfs_client_config
