---
- name: Install and configure Galaxy
  import_tasks: install_galaxy_role_vars.yml

- name: Add test-toolshed 
  template:
    src: 'tool_sheds_conf.xml.j2'
    dest: '{{ laniakea_galaxy_config_dir }}/tool_sheds_conf.xml'

