
- name: Include common galaxy vars
  include_vars:
    file: common.yml

- name: Include vars uwsgi
  include_vars:
    file: zerg-mode.yml
  when: uwsgi_mode == "zerg"


- name: Include galaxy role
  include_role:
    name: galaxyproject.galaxy
    public: true
