---
- name: Include miniconda role
  include_role:
    name: uchida.miniconda
    public: true 
  vars:
    miniconda_prefix: "{{ laniakea_miniconda_prefix }}"
    miniconda_version: "{{ laniakea_miniconda_version }}"
    miniconda_manage_dependencies: "{{ laniakea_manage_dependencies }}"
