---

- name: Include miniconda role
  include_role:
    name: uchida.miniconda
    public: true 
  vars:
    miniconda_prefix: "{{ galaxy_tool_dependency_dir }}/_conda"
    miniconda_version: "4.6.14"
    #ubuntu 20.04 tweak
    miniconda_manage_dependencies: false

