---
- name: Include miniconda role
  include_role:
    name: ansible-miniconda
    public: true
  vars:
    miniconda_prefix: '{{ export_dir }}/tool_deps/_conda'
    miniconda_version: 24.11.2
    miniconda_channels: ['conda-forge', 'bioconda']
