---

- name: Include postgresql role
  include_role:
    name: galaxyproject.postgresql

- name: Include natefoo postgresql role
  include_role:
    name: natefoo.postgresql_objects
    apply:
      become: true
      become_user: postgres
  vars:
    postgresql_backup_dir: /data/backups
    postgresql_backup_local_dir: "{{ '~postgres' | expanduser }}/backups"
    # Python 3 support
    pip_virtualenv_command: /usr/bin/python3 -m virtualenv # usegalaxy_eu.certbot, usegalaxy_eu.tiaas2, galaxyproject.galaxy
    certbot_virtualenv_package_name: python3-virtualenv    # usegalaxy_eu.certbot
    pip_package: python3-pip                               # geerlingguy.pip
    postgresql_objects_users: "{{ galaxy_postgresql_objects_users }}"
    postgresql_objects_databases: "{{ galaxy_postgresql_objects_databases }}"
