---

- name: Install Dependencies
  package:
    name: ['git', 'make', 'python3-psycopg2', 'virtualenv']
- name: Install nginx-extras repository
  apt_repository:
    repo: ppa:galaxyproject/nginx
- name: '[Ubuntu] Prevent nginx update from Ubuntu repository'
  copy:
    src: 'galaxyproject-nginx-pin-700'
    dest: '/etc/apt/preferences.d/'
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"
