---

- name: Include tasks for RockyLinux9
  import_tasks: pretasks_rockylinux9.yml
  when: ansible_distribution == "Rocky"

- name: Include tasks for CentOS7
  import_tasks: pretasks_centos.yml
  when: ansible_distribution == 'CentOS'

- name: '[EL] Install virtualenv for python3'
  pip:
    name: virtualenv
    executable: pip3
  when: ansible_os_family == "RedHat"

- name: '[EL] Disable SELinux'
  selinux:
    policy: targeted
    state: permissive
  when: ansible_os_family == "RedHat"

- name: 'User rules for {{ laniakea_galaxy_user.name }} to allow no passwd for sudo'
  lineinfile:
    dest: '/etc/sudoers'
    state: present
    line: '{{ laniakea_galaxy_user.name }} ALL=(ALL) NOPASSWD:ALL'
    insertafter: EOF
