---

- name: Include tasks for RockyLinux9
  import_tasks: pretasks_rockylinux9.yml
  when: ansible_distribution == "Rocky"

- name: '[Ubuntu] Install Galaxy Dependencies'
  package:
    name: ['git', 'make', 'python3-psycopg2', 'virtualenv']
  when: ansible_os_family == "Debian"

- name: '[EL] Install Galaxy Dependencies'
  package:
    name: ['git', 'make', 'python-psycopg2', 'libselinux-python', 'bzip2', 'python3','python-virtualenv','ca-certificates', 'epel-release', 'acl', 'python3-psycopg2', 'tar', 'python3-virtualenv',  'gcc', 'openssl-devel', 'bzip2-devel', 'libffi-devel', 'zlib-devel', 'xz-devel', 'sqlite-devel']
    state: latest
  when: ansible_os_family == "RedHat" and not ansible_distribution == "Rocky"

- name: Include tasks for CentOS7
  import_tasks: pretasks_centos.yml
  when: ansible_distribution == 'CentOS'

- name: '[EL] Install virtualenv for python3'
  pip:
    name: virtualenv
    executable: pip3
  when: ansible_os_family == "RedHat"

- name: '[EL] Disable SELinux'
  selinux:
    policy: targeted
    state: permissive
  when: ansible_os_family == "RedHat"

- name: 'User rules for {{ laniakea_galaxy_user.name }} to allow no passwd for sudo'
  lineinfile:
    dest: '/etc/sudoers'
    state: present
    line: '{{ laniakea_galaxy_user.name }} ALL=(ALL) NOPASSWD:ALL'
    insertafter: EOF
