---

# - name: Install Dependencies for CentOS7
#   package:
#     name: ['acl', 'bzip2', 'git', 'make', 'python-psycopg2', 'python3-psycopg2', 'tar', 'python3-virtualenv',  'gcc', 'openssl-devel', 'bzip2-devel', 'libffi-devel', 'zlib-devel', 'xz-devel', 'sqlite-devel', 'wget']
 
 - name: Check if python is already installed
   stat: path=/usr/local/bin/python3.7
   register: python3
  
 - name: Download and unarchive Python3.7.11
   unarchive:
     src: https://www.python.org/ftp/python/3.7.11/Python-3.7.11.tgz
     dest: /tmp
     remote_src: yes
   when: not python3.stat.exists

 - name: Configure, compile and install Python3.7
   shell: cd /tmp/Python-3.7.11 && {{ item }}
   with_items:
     - ./configure
     - make
     - make altinstall
   when: not python3.stat.exists

 - name: Python3.6 version priority
   community.general.alternatives:
     name: python3
     link: /usr/bin/python3
     path: /usr/bin/python3.6
     priority: -10

 - name: Correct python3 version selected
   community.general.alternatives:
     name: python3
     link: /usr/bin/python3
     path: /usr/local/bin/python3.7
     priority: 50
# - name: Install correct version of parsedatetime
#   pip:
#     name: parsedatetime
#     version: 2.5

 - name: Install python3 Dependencies for CentOS7
   yum:
     name: 
       - python3-psycopg2
       - python3-virtualenv
     state: present

 - name: Install python3.7 virtualenv
   shell:
     cmd: "/usr/local/bin/python3.7 -m pip install virtualenv"
