---

- name: Include proftpd role
  include_role:
    name: galaxyproject.proftpd
  vars:
    proftpd_options:
      - User: galaxy
      - Group: galaxy
      - DefaultAddress: "{{ansible_default_ipv4.address}}"
    proftpd_sql_db: galaxy@/var/run/postgresql
    galaxy_user: galaxy
    proftpd_sql_user: galaxy
    proftpd_welcome: "galaxy ftp server"
    proftpd_db_user: "galaxyftp"
    proftpd_db_passwd: 'galaxy'
    proftpd_files_path: "{{galaxy_db_dir}}/ftp"
    proftpd_ftp_port: 21
    proftpd_passive_port_low: 30000
    proftpd_passive_port_high: 30009
    set_proftpd_random_password: true
    proftpd_galaxy_auth: yes
    galaxy_ftp_upload_dir: /export/galaxy/database/ftp
    #centos
    ansible_python_interpreter: /usr/bin/python

- name: comment module unique in proftp configuration
  replace:
    dest: /etc/proftpd/modules.conf
    regexp: '^LoadModule mod_unique_id.c'
    replace: '#LoadModule mod_unique_id.c'
  when: ansible_facts['os_family'] == "Debian"

- name: restart proftp after configuration change
  systemd:
    state: restarted
    name: proftpd
  when: ansible_facts['os_family'] == "Debian"

