---

- name: Include systemd role
  include_role:
    name: usegalaxy_eu.galaxy_systemd
  vars:
    galaxy_systemd_mode: mule
    galaxy_zergpool_listen_addr: 127.0.0.1:8080
    galaxy_server_dir: "{{ laniakea_galaxy_server_dir }}"
    galaxy_config_dir: "{{ laniakea_galaxy_config_dir }}" 
    galaxy_venv_dir: "{{ laniakea_galaxy_venv_dir }}"
    galaxy_config_file: "{{ laniakea_galaxy_config_dir }}/galaxy.yml"
