---

- name: Include systemd role
  include_role:
    name: usegalaxy_eu.galaxy_systemd
  vars:
    galaxy_systemd_handler_env: ""
    galaxy_systemd_workflow_scheduler_env: ""
    galaxy_systemd_handlers: 4
