---

- name: Include tusd role
  include_role:
    name: galaxyproject.tusd
  vars:
    tus_upload_store: '{{ database_path }}/tus' 
    galaxy_tusd_port: 1080
    tusd_instances:
      - name: main
        user: "{{ laniakea_galaxy_user.name }}"
        group: "galaxy"
        args:
          - "-host=localhost"
          - "-port={{ galaxy_tusd_port }}"
          - "-upload-dir={{ tus_upload_store }}"
          - "-hooks-http=https://{{ inventory_hostname }}/api/upload/hooks"
          - "-hooks-http-forward-headers=X-Api-Key,Cookie"
              
