---
- name: Converge
  hosts: all
  gather_facts: yes

  #vars:
  #  - pulsar_server_dir: '/opt/pulsar'

  pre_tasks:
    - name: Include tasks for CentOS7
      import_tasks: pretasks_centos.yml
      when: ansible_distribution == 'CentOS'

    - name: Include tasks for RockyLinux9
      import_tasks: pretasks_rockylinux9.yml
      when: ansible_distribution == "Rocky"

  roles:
    - role: ansible-role-laniakea-galaxy
