---
- name: prepare
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap

  post_tasks:

    - name: "[CentOS 7] Solve dependencies before to run"
      yum:
        name:
          - python3
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"


